// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: simpleswap/simpleswap/pool_data.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PoolData struct {
	PoolId      string               `protobuf:"bytes,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
	PoolParams  PoolParams           `protobuf:"bytes,3,opt,name=poolParams,proto3" json:"poolParams"`
	Assets      map[string]PoolAsset `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TotalShares types.Coin           `protobuf:"bytes,5,opt,name=total_shares,json=totalShares,proto3" json:"total_shares" yaml:"total_shares"`
}

func (m *PoolData) Reset()         { *m = PoolData{} }
func (m *PoolData) String() string { return proto.CompactTextString(m) }
func (*PoolData) ProtoMessage()    {}
func (*PoolData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d9c1ac0838a3691, []int{0}
}
func (m *PoolData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolData.Merge(m, src)
}
func (m *PoolData) XXX_Size() int {
	return m.Size()
}
func (m *PoolData) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolData.DiscardUnknown(m)
}

var xxx_messageInfo_PoolData proto.InternalMessageInfo

func (m *PoolData) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *PoolData) GetPoolParams() PoolParams {
	if m != nil {
		return m.PoolParams
	}
	return PoolParams{}
}

func (m *PoolData) GetAssets() map[string]PoolAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *PoolData) GetTotalShares() types.Coin {
	if m != nil {
		return m.TotalShares
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*PoolData)(nil), "simpleswap.simpleswap.PoolData")
	proto.RegisterMapType((map[string]PoolAsset)(nil), "simpleswap.simpleswap.PoolData.AssetsEntry")
}

func init() {
	proto.RegisterFile("simpleswap/simpleswap/pool_data.proto", fileDescriptor_4d9c1ac0838a3691)
}

var fileDescriptor_4d9c1ac0838a3691 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x4d, 0xfa, 0xc5, 0x7b, 0x93, 0xb7, 0x78, 0xcc, 0x7b, 0x4a, 0xac, 0x38, 0x8d, 0x05, 0xa1,
	0x20, 0x4c, 0x68, 0x05, 0x95, 0xee, 0xac, 0x8a, 0x74, 0x57, 0xe2, 0x4a, 0x5d, 0x94, 0xdb, 0x76,
	0xa8, 0xc5, 0xa4, 0x13, 0x32, 0x63, 0x6d, 0xfe, 0x85, 0x3f, 0xab, 0xcb, 0x2e, 0x5d, 0x15, 0x69,
	0xf7, 0x2e, 0xfc, 0x05, 0x32, 0x93, 0x60, 0x23, 0x94, 0xee, 0xce, 0x9d, 0x7b, 0xcf, 0xb9, 0x67,
	0xce, 0x45, 0x47, 0x62, 0x14, 0x84, 0x3e, 0x13, 0x2f, 0x10, 0xba, 0x19, 0x18, 0x72, 0xee, 0x77,
	0x07, 0x20, 0x81, 0x86, 0x11, 0x97, 0x1c, 0xef, 0xac, 0x7b, 0x74, 0x0d, 0xcb, 0xa4, 0xcf, 0x45,
	0xc0, 0x85, 0xdb, 0x03, 0xc1, 0xdc, 0x49, 0xbd, 0xc7, 0x24, 0xd4, 0xdd, 0x3e, 0x1f, 0x8d, 0x13,
	0x5a, 0xf9, 0xff, 0x90, 0x0f, 0xb9, 0x86, 0xae, 0x42, 0xe9, 0x2b, 0xd9, 0xbc, 0x53, 0x4e, 0x93,
	0x7e, 0xf5, 0x23, 0x87, 0x7e, 0x75, 0x38, 0xf7, 0xaf, 0x40, 0x02, 0xde, 0x45, 0x25, 0x65, 0xa6,
	0x3d, 0xb0, 0x4d, 0xc7, 0xac, 0xfd, 0xf6, 0xd2, 0x0a, 0xdf, 0x20, 0xa4, 0x50, 0x07, 0x22, 0x08,
	0x84, 0x9d, 0x77, 0xcc, 0x9a, 0xd5, 0x38, 0xa4, 0x1b, 0x6d, 0xd2, 0xce, 0xf7, 0x60, 0xab, 0x30,
	0x5b, 0x54, 0x0c, 0x2f, 0x43, 0xc5, 0x6d, 0x54, 0x02, 0x21, 0x98, 0x14, 0x76, 0xc1, 0xc9, 0xd7,
	0xac, 0xc6, 0xf1, 0x16, 0x11, 0xe5, 0x88, 0x5e, 0xe8, 0xe9, 0xeb, 0xb1, 0x8c, 0xe2, 0x54, 0x2e,
	0x15, 0xc0, 0x77, 0xe8, 0x8f, 0xe4, 0x12, 0xfc, 0xae, 0x78, 0x84, 0x88, 0x09, 0xbb, 0xa8, 0x5d,
	0xed, 0xd1, 0x24, 0x25, 0xaa, 0x52, 0xa2, 0x69, 0x4a, 0xf4, 0x92, 0x8f, 0xc6, 0xad, 0x7d, 0x45,
	0xff, 0x5c, 0x54, 0xfe, 0xc5, 0x10, 0xf8, 0xcd, 0x6a, 0x96, 0x5c, 0xf5, 0x2c, 0x5d, 0xde, 0xea,
	0xaa, 0xfc, 0x80, 0xac, 0xcc, 0x5e, 0xfc, 0x17, 0xe5, 0x9f, 0x58, 0x9c, 0x46, 0xa2, 0x20, 0x3e,
	0x45, 0xc5, 0x09, 0xf8, 0xcf, 0xcc, 0xce, 0xe9, 0xa5, 0xce, 0x96, 0x5f, 0x68, 0x21, 0x2f, 0x19,
	0x6f, 0xe6, 0xce, 0xcd, 0xd6, 0xd9, 0x6c, 0x49, 0xcc, 0xf9, 0x92, 0x98, 0xef, 0x4b, 0x62, 0xbe,
	0xae, 0x88, 0x31, 0x5f, 0x11, 0xe3, 0x6d, 0x45, 0x8c, 0xfb, 0x83, 0xcc, 0x7d, 0xa6, 0x3f, 0x8e,
	0x15, 0x87, 0x4c, 0xf4, 0x4a, 0xfa, 0x60, 0x27, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x03,
	0xdf, 0x2d, 0x46, 0x02, 0x00, 0x00,
}

func (m *PoolData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalShares.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Assets) > 0 {
		for k := range m.Assets {
			v := m.Assets[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoolData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintPoolData(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintPoolData(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.PoolParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintPoolData(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolData(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovPoolData(uint64(l))
	}
	l = m.PoolParams.Size()
	n += 1 + l + sovPoolData(uint64(l))
	if len(m.Assets) > 0 {
		for k, v := range m.Assets {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovPoolData(uint64(len(k))) + 1 + l + sovPoolData(uint64(l))
			n += mapEntrySize + 1 + sovPoolData(uint64(mapEntrySize))
		}
	}
	l = m.TotalShares.Size()
	n += 1 + l + sovPoolData(uint64(l))
	return n
}

func sovPoolData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolData(x uint64) (n int) {
	return sovPoolData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Assets == nil {
				m.Assets = make(map[string]PoolAsset)
			}
			var mapkey string
			mapvalue := &PoolAsset{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPoolData
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPoolData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthPoolData
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthPoolData
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPoolData
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthPoolData
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthPoolData
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &PoolAsset{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPoolData(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthPoolData
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Assets[mapkey] = *mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolData = fmt.Errorf("proto: unexpected end of group")
)
